### ISSUE TITLE
상세설계서에 대한 수정 부탁 

### ISSUE THREAD

**Issue by hseol** [WBPBP/ff-docs#2]
제가 맘대로 수정하면 안될 것 같아서 여기에 올립니다. 
서버부분에서 입력값에 나이 몸무게 키 부분을 안넣기로 했는데 괜찮다면 제가 수정하고, 아니면 내용 조금 수정 부탁드립니다.  
감사합니다 

수정한 부분
서버에서 수집하는 사용자 데이터는 이메일(ID), 비밀번호, 걸음걸이 패턴이다. 회원가입 시 사용자는 걸음걸이패턴을 제외한 이메일(ID), 비밀번호를 입력한다. 해당 데이터들은 POST를 사용하여 넘겨준다.  이메일을 아이디로 사용하여 사용자에게 간편함을 제공한다. 이때, 코드에는 user_email으로 저장되며, 데이터베이스가 삽입됨과 동시에 사용자 고유의 user_id가 부여된다. 로그인 데이터 역시 POST로 넘겨준다. 사용자 데이터베이스에 저장되어 있는 정보와 일치하면 응답코드 200을 보내고 로그인 실패하면 400을 보내준다. 기타 정보는 GET을 사용하여 전달하고 회원 탈퇴나 정보 변경 등 사용자의 데이터를 삭제할 때는 DELETE를 사용한다. 이때, 삭제하기 전 사용자의 아이디와 비밀번호를 한 번 더 확인 후 삭제한다. 들어오는 입력데이터는 json 형식으로 받고 가공된 걸음걸이 데이터값과 걸음걸이 별로 케이스화 해서 생성된 보고서 내용을 데이버베이스에 저장하고(백업용) 안드로이드에게 넘겨준다. 데이터 값은 그래프로 시각화되고, 보고서 내용은 실제 앱에서 보여주는 보고서 항목에 맞게 뿌려진다.

**Comment by potados99** [comment]
반영하였습니다.

**Comment by hseol** [comment]
감사합니다. 고생많으십니다
