### ISSUE TITLE
상세설계서 수정입니다.

### ISSUE THREAD

**Issue by dobbi030** [WBPBP/ff-docs#3]
상세설계서 수정 본 한글이라 업로드가 안되어 메일로 송부하였습니다.

상세설계서의 컴포넌트 정의 및 설계에서 공용 룰과 모듈 부분 수정하였고 사용자 인터페이스 설계, 시험방법의 시험방법 부분 수정하였습니다.
참고하여 수정 부탁드립니다.

**Comment by potados99** [comment]
반영하였습니다.
