### ISSUE TITLE
상세설계서 데이터 분석파트 수정부탁드립니다.

### ISSUE THREAD

**Issue by Jungjaehee** [WBPBP/ff-docs#4]
상세설계서의 데이터 분석 파트 수정은 다음과 같습니다.

데이터 분석
저수준 데이터 분석기
저수준 데이터 분석기는 신발의 깔창으로부터 블루투스로 왼발, 오른발 구분하는 값과 각 발의 12개의 센서 값, 총 2개의 데이터를 받는다.  첫 번째 데이터에서는 왼발일 경우 0, 오른발일 경우 1이 정수로 입력이 된다. 두 번째 데이터에서는 12개의 센서에 각각 번호를 매겨 정수형 배열 형태로 만들고 그 안에 0~15의 범위를 가지는 값들이 입력이 된다.

전처리 단계 수행 : 족저압 측정은 일정시간동안 정지한 경우와 걷기 모드 총 2가지로 측정된다. 정지모드에서는 일정시간동안 데이터를 받고, 걷기모드에서는 운동이 끝날 때까지 데이터를 받아서 수집하여 특징추출을 하기 위해 압력 합을 구하고 한걸음 단위로 데이터를 나누는 등 적합한 형태로 데이터를 가공하여 준비한다.

특징 추출 단계 수행 : 가공된 데이터로부터 정지한 경우는 양발과 각 발의 앞꿈치/뒤꿈치 무게중심 편향 계산을 진행하고 선형 판별 분석 방법을 활용하여 걷는 동안의 무게중심 편향, 걸음걸이 형태 분류, 질병예측을 위한 각각의 특징 추출을 수행한다.

고수준 데이터 분석기
고수준 데이터 분석기는 걸음걸이 형태 분류, 질병예측을 분류하기 위한 각각의 특징 값들을 입력받아 분류단계를 수행한다. 분류는 다음과 같다.

걸음걸이 형태 분류 :{ 정상걸음, 팔자걸음, 안짱걸음, 학다리 걸음, 11자 걸음 }

질병 예측 : { 척추측만증, 허리디스크, 고관절염, 연골연회증, 관절염 }

걸음걸이 형태 분류의 기준은 총 2가지에 의해 분류된다.

 각 걸음걸이 표준과의 센서별 압력 값 변화 비교 : 걸음걸이마다 보행 단계별 눌려야 하는 센서의 위치나 힘의 수준이 다르기 때문에 저수준 데이터 분석기에서 받아온 한걸음 단위를 가지고 있는 데이터에서 각 걸음걸이와 센서별로 상관관계 분석을 진행하여 높은 상관을 보이는 걸음걸이로 분류가 된다.

 각 걸음걸이 표준과의 족저압 중심 이동 유사도 측정 : 걸음걸이마다 보행단계별 눌리는 센서의 위치가 다르기 때문에 족저압 중심 이동(COP)을 weighted graph로 그린 다음 각 걸음걸이와 그래프 유사도를 측정하여 걸음걸이를 분류한다.

질병예측은 정지한 경우에 양발의 뒤꿈치 압력차가 일정 기준이상인 경우 척추측만증을 의심하고 있으며 각 걸음걸이별로 유발될 수 있는 질병들을 예측한다.

**Comment by potados99** [comment]
반영하였습니다.
